#!/usr/bin/env bash
# Installs nginx web server

# Update the system package list
sudo apt update

# Install Nginx (if not already installed)
sudo apt install nginx -y

# Create a custom Nginx configuration file for the redirection
echo 'server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}' | sudo tee /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the new configuration
sudo service nginx reload

# Display a message indicating successful configuration
echo "Nginx has been configured to perform a 301 Moved Permanently redirect from /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4"
