#!/usr/bin/env bash

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create an index.html file with the desired content (optional)
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Create a Nginx server block configuration for redirection
echo 'server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}' | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx to apply the configuration
sudo service nginx restart
