#!/usr/bin/env bash
# Installs nginx web server
# Update the system package list
sudo apt update

# Install Nginx (if not already installed)
sudo apt install nginx -y

# Create a custom Nginx configuration file for the custom 404 page
echo 'server {
    listen 80;
    server_name localhost;

    error_page 404 /custom_404.html;

    location = /custom_404.html {
        root /var/www/html;
        internal;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}' | sudo tee /etc/nginx/sites-available/custom_404
service nginx restart
