#!/usr/bin/env bash
# Installs nginx web server
# Update the system package list
sudo apt update

# Install Nginx (if not already installed)
sudo apt install nginx -y

# Create a custom Nginx configuration file for the custom 404 page
echo 'server {
    listen 80;
    server_name localhost;

    error_page 404 /custom_404.html;

    location = /custom_404.html {
        root /var/www/html;
        internal;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}' | sudo tee /etc/nginx/sites-available/custom_404

# Create a custom 404 HTML page
echo '<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <center><h1>Ceci n&apos;est pas une page</h1></center>
</body>
</html>' | sudo tee /var/www/html/custom_404.html

# Create a symbolic link to enable the configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Test Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the new configuration
sudo service nginx reload

# Display a message indicating successful configuration
echo "Nginx has been configured to display a custom 404 page."
