#!/bin/bash

# Replace 'server01' and '8.8.8.8' with your actual server information
server="server01"
ip="8.8.8.8"
keyfile="/root/.ssh/id_rsa"  # Path to your private key

# Use ssh with the private key and user
ssh -i "$keyfile" ubuntu@$ip
